#!/bin/sh

#####################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗   #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝   #                                    
################# By: AlexisGuarin321  ##############

################################## *ENV VAR* ###################################

export PATH="${PATH}:${HOME}/.config/bspwm/bin"

################################ *COLOR VARS* ##################################

black=#000000
gray=#1c1e27
red=#dd6777
green=#90ceaa
yellow=ecd3a0
blue=#010A15
magenta=c296eb
cyan=#93cee9
white=#F4F4F4

################################ *FUNCTIONS* ###################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }


############################# *AUTOSTART APPS* #################################

# Run keybindings daemon.
pgrep -x sxhkd > /dev/null || sxhkd &

# Run EWW.
$HOME/.local/bin/eww -c $HOME/.config/eww/bar --restart open bar &

# Run notification daemon.
dunst --config $HOME/.config/dunst/dunstrc &

# Run Picom.
picom --config $HOME/.config/picom/picom.conf &

# Run polkit daemon if doesn't started.
[ -n "$(pidof xfce-polkit)" ] || /usr/lib/xfce-polkit/xfce-polkit &

# Run power manager.
xfce4-power-manager &

# Run mpd if doesn't started.
[ -n "$(pidof mpd)" ] || mpd &

# Execute bspwm-specific scripts.
bspfloat &

# Start X wallpaper.
feh --no-fehbg --bg-fill $HOME/Pictures/bg.jpg

# Fix cursor.
xsetroot -cursor_name left_ptr

# set keymap else
setxkbmap latam


############################## *WINDOWS RULES* #################################

bspc monitor -d 1 2 3 4 5 6  

rule -a kitty                       follow=on focus=on
rule -a geany                       follow=on focus=on
rule -a brave                       state=floating
rule mpv                            state=floating
rule feh                            state=floating

############################## *CONFIGURARTION* ##############################

bspc subscribe node_state | while read -r _ _ _ _ state flag; do
    if [ "$state" != "fullscreen" ]; then
        continue
    fi
    if [ "$flag" == on ]; then
        $HOME/.local/bin/eww -c $HOME/.config/eww/bar close-all
  else
        $HOME/.local/bin/eww -c $HOME/.config/eww/bar open bar
    fi
done &

############################## *WINDOW CONFIG* ###############################
config left_padding 54
config border_width -7
config window_gap 3
config split_ratio 0.50

config borderless_monocle true
config gapless_monocle true
config focus_follows_pointer true

bspc config normal_border_color "$black"
bspc config focused_border_color "$blue"
config presel_feedback_color "$gray"
pkill borders ; borders &
